name: CI

on:
  pull_request:
  push:
    branches: [ "main", "develop" ]

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: 8.4

      - name: Install dependencies
        run: composer install --no-interaction

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse src

      - name: Run PHPUnit
        run: vendor/bin/phpunit
        